AWSTemplateFormatVersion: "2010-09-09"
Description: A CloudFormation template to create a Route53 Hosted Zone
Parameters:
  DomainName:
    Type: String
    Default: jasongoff.neptune19.com
Resources:
  StaticBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: resume.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: PublicPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref StaticBucket
                - /*
      Bucket: !Ref StaticBucket
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - StaticBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - StaticBucket
          - DomainName
    Description: Name of S3 bucket to hold website content
