AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 284148388796

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: Jason DC Goff
      AccountId: '284148388796'
      RootEmail: jason@goff.me.uk
      Alias: jasongoff

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole


